# Generated by Django 3.1 on 2020-10-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0009_auto_20200923_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItemTextile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Закупочная стоимость')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_change', models.DateField(blank=True, null=True, verbose_name='Дата изменения')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.textile', verbose_name='Текстиль')),
            ],
        ),
        migrations.CreateModel(
            name='StorageItemCornice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Закупочная стоимость')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_change', models.DateField(blank=True, null=True, verbose_name='Дата изменения')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornice', verbose_name='Текстиль')),
            ],
        ),
    ]
