# Generated by Django 3.1 on 2020-10-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20200923_1023'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitemcornice',
            name='type_p',
            field=models.CharField(blank=True, default='Карнизы', max_length=100, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='storageitemtextile',
            name='type_p',
            field=models.CharField(blank=True, default='Текстиль', max_length=100, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='storageitemcornice',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornice', verbose_name='Карнизы'),
        ),
    ]
