# Generated by Django 3.1 on 2020-10-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20201029_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitemcornice',
            name='reserve',
            field=models.IntegerField(default=1, verbose_name='Резерв'),
        ),
        migrations.AddField(
            model_name='storageitemtextile',
            name='reserve',
            field=models.IntegerField(default=1, verbose_name='Резерв'),
        ),
    ]
