# Generated by Django 3.1 on 2020-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20201030_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitemcornice',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storageitemcornice',
            name='reserve',
            field=models.IntegerField(default=0, verbose_name='Резерв'),
        ),
        migrations.AlterField(
            model_name='storageitemtextile',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storageitemtextile',
            name='reserve',
            field=models.IntegerField(default=0, verbose_name='Резерв'),
        ),
    ]
