# Generated by Django 3.1 on 2020-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20201030_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitemtextile',
            name='date_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
