# Generated by Django 3.1 on 2020-10-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0090_order_discount_status'),
        ('storage', '0005_auto_20201030_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItemTextileReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.storageitemtextile', verbose_name='Текстиль')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
