# Generated by Django 3.1 on 2020-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storageitemtextilereserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageitemtextile',
            name='date_change',
        ),
        migrations.RemoveField(
            model_name='storageitemtextile',
            name='reserve',
        ),
        migrations.AddField(
            model_name='storageitemtextilereserve',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
