# Generated by Django 3.1 on 2020-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20201030_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitemcornice',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storageitemtextile',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storageitemtextilereserve',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
    ]
