# Generated by Django 3.1 on 2020-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20201105_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitemcornice',
            name='price_f',
            field=models.FloatField(default=0, verbose_name='Цена фирмы'),
        ),
        migrations.AddField(
            model_name='storageitemtextile',
            name='price_f',
            field=models.FloatField(default=0, verbose_name='Цена фирмы'),
        ),
        migrations.AlterField(
            model_name='storageitemcornice',
            name='reserve',
            field=models.FloatField(default=0, verbose_name='Резерв'),
        ),
    ]
