# Generated by Django 3.1 on 2020-08-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorniceManufact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='TextileManufact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Высота')),
                ('price_opt', models.FloatField(blank=True, null=True, verbose_name='Цена отп')),
                ('price_pog', models.FloatField(blank=True, null=True, verbose_name='Цена пог метра')),
                ('price_rul', models.FloatField(blank=True, null=True, verbose_name='Цена рулон')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.textilemanufact')),
            ],
        ),
        migrations.CreateModel(
            name='Cornice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('long', models.FloatField(verbose_name='Длина, мм')),
                ('price_opt', models.FloatField(blank=True, null=True, verbose_name='Цена отп')),
                ('price_pog', models.FloatField(blank=True, null=True, verbose_name='Цена пог метра')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.cornicemanufact')),
            ],
        ),
    ]
