# Generated by Django 3.1 on 2020-08-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornice',
            name='long',
            field=models.IntegerField(verbose_name='Длина, мм'),
        ),
        migrations.AlterField(
            model_name='cornice',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.cornicemanufact', verbose_name='Производитель'),
        ),
    ]
