# Generated by Django 3.1 on 2020-08-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20200812_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.textilemanufact', verbose_name='Производитель'),
        ),
    ]
