# Generated by Django 3.1 on 2020-09-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='textilemanufact',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
    ]
