# Generated by Django 3.1 on 2020-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_textilemanufact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='textile',
            name='collection',
            field=models.CharField(blank=True, max_length=100, verbose_name='Коллекция'),
        ),
    ]
