# Generated by Django 3.1 on 2020-09-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_textile_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornicemanufact',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
    ]
