# Generated by Django 3.1 on 2020-09-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_cornicemanufact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.textilemanufact', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='TextileCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Коллекция')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.textilemanufact', verbose_name='Производитель')),
            ],
        ),
        migrations.AlterField(
            model_name='textile',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.textilecollection', verbose_name='Коллекция'),
        ),
    ]
