# Generated by Django 3.1 on 2020-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20200922_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='textile',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Модель'),
        ),
    ]
