# Generated by Django 3.1 on 2020-09-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_textile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='Цвет'),
        ),
        migrations.CreateModel(
            name='CorniceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Коллекция')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornicemanufact', verbose_name='Производитель')),
            ],
        ),
        migrations.AddField(
            model_name='cornice',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornicecollection', verbose_name='Коллекция'),
        ),
    ]
