# Generated by Django 3.1 on 2020-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20200923_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornicemanufact',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='cornicemanufact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='textilemanufact',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='textilemanufact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
