# Generated by Django 3.1 on 2020-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20201030_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornicemanufact',
            name='type_p',
            field=models.CharField(default='Карнизы', max_length=100, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='textilemanufact',
            name='type_p',
            field=models.CharField(default='Текстиль', max_length=100, verbose_name='Тип'),
        ),
    ]
