# Generated by Django 3.1 on 2020-10-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20201030_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cornice',
            name='price_pog',
        ),
        migrations.RemoveField(
            model_name='textile',
            name='price_pog',
        ),
        migrations.RemoveField(
            model_name='textile',
            name='price_rul',
        ),
    ]
