# Generated by Django 3.1 on 2020-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_auto_20201031_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='textile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Обозначение'),
        ),
    ]
