# Generated by Django 3.1 on 2020-11-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_textile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Высота'),
        ),
    ]
