# Generated by Django 3.1 on 2020-11-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_auto_20201102_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Цвет'),
        ),
    ]
