# Generated by Django 3.1 on 2020-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_auto_20201102_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='textile',
            name='currency',
            field=models.CharField(blank=True, default='руб.', max_length=100, null=True, verbose_name='Валюта'),
        ),
    ]
