# Generated by Django 3.1 on 2020-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_textile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='textile',
            name='type_i',
            field=models.CharField(blank=True, default='шт', max_length=100, null=True, verbose_name='Тип измерения'),
        ),
    ]
