# Generated by Django 3.1 on 2020-11-08 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_textile_type_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorniceAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type_p', models.CharField(default=None, max_length=100, verbose_name='Наименование')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('cornice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.cornice', verbose_name='Карниз')),
            ],
        ),
    ]
