# Generated by Django 3.1 on 2020-11-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_corniceadditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='corniceadditional',
            name='category',
            field=models.CharField(default=None, max_length=100, verbose_name='Категория'),
        ),
    ]
