# Generated by Django 3.1 on 2020-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_corniceadditional_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corniceadditional',
            name='type_p',
            field=models.CharField(default=None, max_length=100, verbose_name='Тип'),
        ),
    ]