# Generated by Django 3.1 on 2020-11-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20201108_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corniceadditional',
            name='cornice',
        ),
    ]
