# Generated by Django 3.1 on 2020-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_remove_corniceadditional_cornice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornice',
            name='additional',
            field=models.ManyToManyField(to='materials.CorniceAdditional', verbose_name='Допы'),
        ),
    ]
