# Generated by Django 3.1 on 2020-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_cornice_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='type_i',
            field=models.CharField(blank=True, default='м', max_length=100, null=True, verbose_name='Тип измерения'),
        ),
    ]
