# Generated by Django 3.1 on 2020-11-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_auto_20201118_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorniceAdditionalOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=100, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type_p', models.CharField(default=None, max_length=100, verbose_name='Тип')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='CorniceCollectionColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.RemoveField(
            model_name='cornice',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='corniceadditional',
            name='price',
        ),
        migrations.RemoveField(
            model_name='corniceadditional',
            name='type_p',
        ),
        migrations.AddField(
            model_name='corniceadditional',
            name='options',
            field=models.ManyToManyField(to='materials.CorniceAdditionalOptions', verbose_name='Варианты'),
        ),
        migrations.AddField(
            model_name='cornicecollection',
            name='color',
            field=models.ManyToManyField(to='materials.CorniceCollectionColor', verbose_name='Цвета'),
        ),
    ]
