# Generated by Django 3.1 on 2020-11-19 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_auto_20201118_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='corniceadditional',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornicecollection', verbose_name='Коллекция'),
        ),
    ]
