# Generated by Django 3.1 on 2020-11-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_corniceadditional_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corniceadditional',
            name='options',
        ),
        migrations.RemoveField(
            model_name='corniceadditionaloptions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='corniceadditionaloptions',
            name='name',
        ),
        migrations.AddField(
            model_name='corniceadditionaloptions',
            name='additional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.corniceadditional', verbose_name='Доп'),
        ),
    ]
