# Generated by Django 3.1 on 2020-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20201119_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textilecollection',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Коллекция'),
        ),
    ]
