# Generated by Django 3.1.7 on 2021-05-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_auto_20201123_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='textile',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Снят с производства'),
        ),
        migrations.AlterField(
            model_name='textile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Обозначение'),
        ),
    ]
