# Generated by Django 3.1 on 2020-08-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('pass_series', models.CharField(max_length=10, verbose_name='Серия')),
                ('pass_number', models.CharField(max_length=10, verbose_name='Номер')),
                ('pass_issued', models.CharField(max_length=300, verbose_name='Выдан')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('date', models.CharField(blank=True, max_length=100, verbose_name='Дата договора')),
                ('price', models.FloatField(max_length=100, verbose_name='Стоимость')),
                ('price_w', models.CharField(blank=True, max_length=500, verbose_name='Стоимость прописью')),
                ('prepay', models.FloatField(max_length=100, verbose_name='Размер предоплаты')),
                ('prepay_duration', models.FloatField(max_length=100, verbose_name='Предоплата в течение')),
                ('work_duration', models.FloatField(max_length=100, verbose_name='Длительность работ')),
                ('date_acceptance', models.CharField(blank=True, max_length=100, verbose_name='Дата приемки')),
                ('date_finish', models.CharField(blank=True, max_length=100, verbose_name='Дата выполнения')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer', verbose_name='Заказчик')),
            ],
        ),
    ]
