# Generated by Django 3.1 on 2020-08-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название помещения')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='contract',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.specification', verbose_name='Спецификация'),
        ),
    ]
