# Generated by Django 3.1 on 2020-09-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('works', '0001_initial'),
        ('orders', '0002_auto_20200813_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='cornice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.cornice', verbose_name='Корнизы'),
        ),
        migrations.AddField(
            model_name='specification',
            name='full_price',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='specification',
            name='sewing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work', verbose_name='Работы'),
        ),
        migrations.AddField(
            model_name='specification',
            name='textile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.textile', verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='specification',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Версия'),
        ),
    ]
