# Generated by Django 3.1 on 2020-09-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('works', '0001_initial'),
        ('orders', '0003_auto_20200904_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='cornice',
        ),
        migrations.AddField(
            model_name='specification',
            name='cornice',
            field=models.ManyToManyField(to='materials.Cornice', verbose_name='Корнизы'),
        ),
        migrations.RemoveField(
            model_name='specification',
            name='sewing',
        ),
        migrations.AddField(
            model_name='specification',
            name='sewing',
            field=models.ManyToManyField(to='works.Work', verbose_name='Работы'),
        ),
        migrations.RemoveField(
            model_name='specification',
            name='textile',
        ),
        migrations.AddField(
            model_name='specification',
            name='textile',
            field=models.ManyToManyField(to='materials.Textile', verbose_name='Материалы'),
        ),
    ]
