# Generated by Django 3.1 on 2020-09-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200904_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_acceptance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата приемки'),
        ),
    ]
