# Generated by Django 3.1 on 2020-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('works', '0001_initial'),
        ('orders', '0005_auto_20200904_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='cornice',
            field=models.ManyToManyField(blank=True, to='materials.Cornice', verbose_name='Корнизы'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='sewing',
            field=models.ManyToManyField(blank=True, to='works.Work', verbose_name='Работы'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='textile',
            field=models.ManyToManyField(blank=True, to='materials.Textile', verbose_name='Материалы'),
        ),
        migrations.CreateModel(
            name='OrdetItemTextile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ManyToManyField(blank=True, to='materials.Textile', verbose_name='Материалы')),
            ],
        ),
    ]
