# Generated by Django 3.1 on 2020-09-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0006_auto_20200904_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdetItemTextile',
            new_name='OrderItemTextile',
        ),
    ]
