# Generated by Django 3.1 on 2020-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0007_auto_20200904_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtextile',
            name='item',
            field=models.ManyToManyField(blank=True, to='materials.Textile', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='orderitemtextile',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='textile',
            field=models.ManyToManyField(blank=True, to='orders.OrderItemTextile', verbose_name='Материалы'),
        ),
    ]
