# Generated by Django 3.1 on 2020-09-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0008_auto_20200904_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='textile',
        ),
        migrations.RemoveField(
            model_name='orderitemtextile',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitemtextile',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.textile', verbose_name='Материал'),
        ),
    ]
