# Generated by Django 3.1 on 2020-09-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0009_auto_20200904_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtextile',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.textile', verbose_name='Материал'),
        ),
    ]
