# Generated by Django 3.1 on 2020-09-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0010_auto_20200904_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemTextile',
            new_name='OrderItemTextile1',
        ),
    ]
