# Generated by Django 3.1 on 2020-09-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200904_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='cornice',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='full_price',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='sewing',
        ),
        migrations.AddField(
            model_name='orderitemtextile1',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.specification', verbose_name='Спецификация'),
        ),
    ]
