# Generated by Django 3.1 on 2020-09-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0012_auto_20200904_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCornice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.cornice', verbose_name='Карнизы')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.specification', verbose_name='Спецификация')),
            ],
        ),
    ]
