# Generated by Django 3.1 on 2020-09-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        ('orders', '0013_orderitemcornice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemWorkSewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work', verbose_name='Работы')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.specification', verbose_name='Спецификация')),
            ],
        ),
    ]
