# Generated by Django 3.1 on 2020-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitemworksewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'No success'), ('S', 'Success')], max_length=1),
        ),
    ]
