# Generated by Django 3.1 on 2020-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_specification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='status',
            field=models.BooleanField(blank=True, default=0, max_length=1),
        ),
    ]
