# Generated by Django 3.1 on 2020-09-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200905_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='specification',
        ),
        migrations.AddField(
            model_name='specification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.contract', verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='status',
            field=models.BooleanField(blank=True, default=0, max_length=1, verbose_name='Статус'),
        ),
    ]
