# Generated by Django 3.1 on 2020-09-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        ('orders', '0017_auto_20200905_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.contract', verbose_name='Договор'),
        ),
        migrations.CreateModel(
            name='OrderItemWorkAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work', verbose_name='Работы')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.specification', verbose_name='Спецификация')),
            ],
        ),
    ]
