# Generated by Django 3.1 on 2020-09-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='contract',
        ),
        migrations.AddField(
            model_name='specification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ'),
        ),
    ]
