# Generated by Django 3.1 on 2020-09-06 00:12

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200905_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, default=orders.models.GetCountOrder, max_length=100, verbose_name='Номер'),
        ),
    ]
