# Generated by Django 3.1 on 2020-09-06 15:32

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200906_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, default=orders.models.GetCountOrder, max_length=100, null=True, verbose_name='Номер'),
        ),
    ]
