# Generated by Django 3.1 on 2020-09-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200906_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма'),
        ),
    ]
