# Generated by Django 3.1 on 2020-09-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200906_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(blank=True, default=0, max_length=1, verbose_name='Статус'),
        ),
    ]
