# Generated by Django 3.1 on 2020-09-06 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.room', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='version',
            field=models.CharField(choices=[('EC', 'Econom'), ('ST', 'Standart'), ('PR', 'Premium')], default='EC', max_length=2, verbose_name='Версия'),
        ),
    ]
