# Generated by Django 3.1 on 2020-09-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200906_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='assembly_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма монтаж'),
        ),
        migrations.AddField(
            model_name='specification',
            name='cornice_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма корнизы'),
        ),
        migrations.AddField(
            model_name='specification',
            name='sewing_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма пошив'),
        ),
        migrations.AddField(
            model_name='specification',
            name='textile_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма текстиль'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='version',
            field=models.CharField(choices=[('Econom', 'Econom'), ('Standart', 'Standart'), ('Premium', 'Premium')], default='Econom', max_length=10, verbose_name='Версия'),
        ),
    ]
