# Generated by Django 3.1 on 2020-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pass_date',
            field=models.CharField(default=0, max_length=10, verbose_name='Дата выдачи'),
        ),
    ]
