# Generated by Django 3.1 on 2020-09-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200909_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('Econom', 'Econom'), ('Standart', 'Standart'), ('Premium', 'Premium')], default='Econom', max_length=10, verbose_name='Версия')),
                ('total', models.CharField(blank=True, max_length=100, verbose_name='Общая сумма')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.offerversion', verbose_name='Версия')),
            ],
        ),
    ]
