# Generated by Django 3.1 on 2020-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_offer_offerversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='work_start',
            field=models.FloatField(default=5, max_length=100, verbose_name='Начало работ (через)'),
        ),
    ]
