# Generated by Django 3.1 on 2020-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_contract_work_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='garant',
            field=models.FloatField(default=1, max_length=100, verbose_name='Гарантийный срок)'),
        ),
    ]
