# Generated by Django 3.1 on 2020-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20200910_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='garant',
            field=models.IntegerField(default=1, verbose_name='Гарантийный срок)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prepay',
            field=models.IntegerField(verbose_name='Размер предоплаты'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prepay_duration',
            field=models.IntegerField(verbose_name='Предоплата в течение'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_duration',
            field=models.IntegerField(verbose_name='Длительность работ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_start',
            field=models.IntegerField(default=5, verbose_name='Начало работ (через)'),
        ),
    ]
