# Generated by Django 3.1 on 2020-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20200910_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_doc',
            field=models.FileField(blank=True, upload_to='contract'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
