# Generated by Django 3.1 on 2020-09-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20200910_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contract_doc',
        ),
        migrations.CreateModel(
            name='OrderDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_doc', models.FileField(blank=True, upload_to='contract')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
