# Generated by Django 3.1 on 2020-09-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20200910_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланирован'), (1, 'КП подготовлено'), (2, 'КП утверждено'), (3, 'Договор подготовлен'), (4, 'Договор подписан'), (5, 'Аванс получен'), (6, 'Ткани заказаны')], default=0, verbose_name='Статус'),
        ),
    ]
