# Generated by Django 3.1 on 2020-09-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20200910_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Платеж')),
                ('type_pay', models.IntegerField(choices=[(0, 'Первичный аванс'), (1, 'Платеж')], default=0, verbose_name='Вариант платежа')),
                ('type_money', models.IntegerField(choices=[(0, 'Безналичный'), (1, 'Наличный')], default=0, verbose_name='Тип платежа')),
                ('receipt', models.CharField(max_length=100, verbose_name='Чек')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
