# Generated by Django 3.1 on 2020-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.FloatField(default=0, max_length=100, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Платеж'),
        ),
    ]
