# Generated by Django 3.1 on 2020-09-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcornice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderitemtextile1',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderitemworkassembly',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderitemworksewing',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ'),
        ),
    ]
