# Generated by Django 3.1 on 2020-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20200910_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtextile1',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Версия'),
        ),
    ]
