# Generated by Django 3.1 on 2020-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_orderitemtextile1_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcornice',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='orderitemworkassembly',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='orderitemworksewing',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Версия'),
        ),
    ]
