# Generated by Django 3.1 on 2020-09-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20200910_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtextile1',
            name='ordered',
            field=models.BooleanField(choices=[(0, 'Не заказан'), (1, 'Заказан')], default=0, verbose_name='Состояние заказа'),
        ),
    ]
