# Generated by Django 3.1 on 2020-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_orderitemtextile1_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtextile1',
            name='payed',
            field=models.BooleanField(choices=[(0, 'Не оплачен'), (1, 'Оплачен')], default=0, verbose_name='Состояние оплаты'),
        ),
    ]
