# Generated by Django 3.1 on 2020-09-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200812_1534'),
        ('orders', '0047_orderitemtextile1_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланирован'), (1, 'КП подготовлено'), (2, 'КП утверждено'), (3, 'Договор подготовлен'), (4, 'Договор подписан'), (5, 'Аванс получен'), (6, 'Ткани заказаны'), (7, 'Ткани оплачены')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='ordered',
            field=models.BooleanField(choices=[(0, 'Не заказан'), (1, 'Заказ отправлен'), (2, 'Получен ответ'), (3, 'Заказан'), (4, 'Отгружены'), (5, 'В наличии')], default=0, verbose_name='Состояние заказа'),
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.ManyToManyField(to='orders.OrderItemTextile1', verbose_name='Заказанный материал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.textilemanufact', verbose_name='Поставщик')),
            ],
        ),
    ]
