# Generated by Django 3.1 on 2020-09-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_auto_20200911_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='status',
            field=models.BooleanField(choices=[(0, 'Не отправлен'), (1, 'Отправлен')], default=0, verbose_name='Состояние заказа'),
        ),
    ]
