# Generated by Django 3.1 on 2020-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_supplierorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказ отправлен'), (2, 'Получен ответ'), (3, 'Заказан'), (4, 'Отгружены'), (5, 'В наличии')], default=0, verbose_name='Состояние заказа'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не отправлен'), (1, 'Отправлен')], default=0, verbose_name='Состояние заказа'),
        ),
    ]
