# Generated by Django 3.1 on 2020-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_auto_20200911_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказ отправлен'), (2, 'Заказан'), (3, 'Оплачен'), (4, 'Отгружены'), (5, 'В наличии')], default=0, verbose_name='Состояние заказа'),
        ),
    ]
