# Generated by Django 3.1 on 2020-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_auto_20200914_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.IntegerField(choices=[(0, 0), (1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60), (7, 70), (8, 80), (9, 90), (10, 100)], default=0, verbose_name='Статус'),
        ),
    ]
