# Generated by Django 3.1 on 2020-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_order_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source_t',
            field=models.IntegerField(choices=[(0, 'От Партнеров'), (1, 'Социальные сети'), (2, 'Маркетплейс'), (3, 'Телефон'), (4, 'Салон')], default=0, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_css',
            field=models.IntegerField(choices=[(0, 'secondary'), (1, 'secondary'), (2, 'secondary'), (3, 'info'), (4, 'info'), (5, 'primary'), (6, 'primary'), (7, 'primary')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pass_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pass_issued',
            field=models.CharField(blank=True, max_length=300, verbose_name='Выдан'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pass_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pass_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='progress',
            field=models.IntegerField(choices=[(0, 0), (1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60), (7, 70), (8, 80), (9, 90), (10, 100)], default=0, verbose_name='Прогресс'),
        ),
    ]
