# Generated by Django 3.1 on 2020-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_auto_20200916_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
    ]
