# Generated by Django 3.1 on 2020-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ManyToManyField(to='orders.Order', verbose_name='Заказ'),
        ),
    ]
