# Generated by Django 3.1 on 2020-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_auto_20200916_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='version',
            field=models.CharField(choices=[(0, 'Econom'), (1, 'Standart'), (2, 'Premium')], default=0, max_length=10, verbose_name='Версия'),
        ),
    ]
