# Generated by Django 3.1 on 2020-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_auto_20200918_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='version',
            field=models.CharField(choices=[('Econom', 'Econom'), ('Standart', 'Standart'), ('Premium', 'Premium')], default='Econom', max_length=10, verbose_name='Версия'),
        ),
    ]
