# Generated by Django 3.1 on 2020-09-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_auto_20200918_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtextile1',
            name='ordered_icon',
            field=models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'fa-dot-circle-o'), (2, 'fa-certificate'), (3, 'fa-rub'), (4, 'fa-arrow-circle-o-down'), (5, 'fa-check-circle-o')], default=0, verbose_name='Состояние заказа icon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email'),
        ),
    ]
