# Generated by Django 3.1 on 2020-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_auto_20200920_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказ отправлен'), (2, 'Заказан'), (3, 'Оплачен'), (4, 'Отгружены'), (5, 'В наличии'), (6, 'Отсутствует у поставщика')], default=0, verbose_name='Состояние заказа'),
        ),
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='ordered_icon',
            field=models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'fa-dot-circle-o'), (2, 'fa-certificate'), (3, 'fa-rub'), (4, 'fa-arrow-circle-o-down'), (5, 'fa-check-circle-o-down'), (6, 'fa-exclamation')], default=0, verbose_name='Состояние заказа icon'),
        ),
    ]
