# Generated by Django 3.1 on 2020-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_auto_20200921_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemtextile1',
            name='payed',
        ),
        migrations.AddField(
            model_name='order',
            name='cornice_state',
            field=models.IntegerField(choices=[(0, 'Не заказаны'), (1, 'Заказаны'), (2, 'Оплачены'), (3, 'Отгружены')], default=0, verbose_name='Состояние по карнизам'),
        ),
        migrations.AddField(
            model_name='order',
            name='textile_state',
            field=models.IntegerField(choices=[(0, 'Не заказаны'), (1, 'Заказаны'), (2, 'Оплачены'), (3, 'Отгружены')], default=0, verbose_name='Состояние по текстилю'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланирован'), (1, 'КП подготовлено'), (2, 'КП утверждено'), (3, 'Договор подготовлен'), (4, 'Договор подписан'), (5, 'Аванс получен'), (6, 'Материалы заказаны'), (7, 'Материалы оплачены'), (8, 'Материалы отгружены')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_css',
            field=models.IntegerField(choices=[(0, 'secondary'), (1, 'secondary'), (2, 'secondary'), (3, 'info'), (4, 'info'), (5, 'primary'), (6, 'primary'), (7, 'primary'), (8, 'primary')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='ordered_icon',
            field=models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target'), (2, 'disc'), (3, 'dollar-sign'), (4, 'arrow-down-circle'), (5, 'arrow-down-circle'), (6, 'alert-circle')], default=0, verbose_name='Состояние заказа icon'),
        ),
    ]
