# Generated by Django 3.1 on 2020-09-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_auto_20200921_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcornice',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказ отправлен'), (2, 'Заказан'), (3, 'Оплачен'), (4, 'Отгружены'), (5, 'В наличии'), (6, 'Отсутствует у поставщика')], default=0, verbose_name='Состояние заказа'),
        ),
        migrations.AddField(
            model_name='orderitemcornice',
            name='ordered_icon',
            field=models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target'), (2, 'disc'), (3, 'dollar-sign'), (4, 'arrow-down-circle'), (5, 'arrow-down-circle'), (6, 'alert-circle')], default=0, verbose_name='Состояние заказа icon'),
        ),
    ]
