# Generated by Django 3.1 on 2020-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_auto_20200921_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Поставщик'),
        ),
    ]
