# Generated by Django 3.1 on 2020-09-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_cornicemanufact_email'),
        ('orders', '0063_auto_20200921_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.textilemanufact', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='SupplierOrderCornice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='email')),
                ('status', models.IntegerField(choices=[(0, 'Не отправлен'), (1, 'Отправлен'), (2, 'Получен ответ')], default=0, verbose_name='Состояние заказа')),
                ('materials', models.ManyToManyField(to='orders.OrderItemCornice', verbose_name='Заказанный материал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornicemanufact', verbose_name='Поставщик')),
            ],
        ),
    ]
