# Generated by Django 3.1 on 2020-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_auto_20200921_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work_state',
            field=models.IntegerField(choices=[(0, 'Не заказаны'), (1, 'Заказаны'), (2, 'Оплачены'), (3, 'Отгружены')], default=0, verbose_name='Состояние по карнизам'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Доход'), (1, 'Расход')], default=0, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланирован'), (1, 'КП подготовлено'), (2, 'КП утверждено'), (3, 'Договор подготовлен'), (4, 'Договор подписан'), (5, 'Аванс получен'), (6, 'Материалы заказаны'), (7, 'Материалы оплачены'), (8, 'Материалы отгружены'), (9, 'Работы заказаны'), (10, 'Заказ выдан')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_css',
            field=models.IntegerField(choices=[(0, 'secondary'), (1, 'secondary'), (2, 'secondary'), (3, 'info'), (4, 'info'), (5, 'primary'), (6, 'primary'), (7, 'primary'), (8, 'primary'), (9, 'primary'), (10, 'success')], default=0, verbose_name='Статус'),
        ),
    ]
