# Generated by Django 3.1 on 2020-09-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_auto_20200921_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='type_p',
        ),
    ]
