# Generated by Django 3.1 on 2020-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_offerversion_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemworksewing',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказана'), (1, 'Заказана')], default=0, verbose_name='Состояние заказа'),
        ),
        migrations.AddField(
            model_name='orderitemworksewing',
            name='ordered_icon',
            field=models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target')], default=0, verbose_name='Состояние заказа icon'),
        ),
    ]
