# Generated by Django 3.1 on 2020-09-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_auto_20200923_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemworkassembly',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказан')], default=0, verbose_name='Состояние заказа'),
        ),
        migrations.AddField(
            model_name='orderitemworkassembly',
            name='ordered_icon',
            field=models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target')], default=0, verbose_name='Состояние заказа icon'),
        ),
        migrations.AlterField(
            model_name='orderitemworksewing',
            name='ordered',
            field=models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказан')], default=0, verbose_name='Состояние заказа'),
        ),
    ]
