# Generated by Django 3.1 on 2020-09-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        ('orders', '0069_auto_20200924_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemWorkHanging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Версия')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('ordered', models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказан')], default=0, verbose_name='Состояние заказа')),
                ('ordered_icon', models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target')], default=0, verbose_name='Состояние заказа icon')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работы')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.specification', verbose_name='Спецификация')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemWorkDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Версия')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('ordered', models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказан')], default=0, verbose_name='Состояние заказа')),
                ('ordered_icon', models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target')], default=0, verbose_name='Состояние заказа icon')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Работы')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.specification', verbose_name='Спецификация')),
            ],
        ),
    ]
