# Generated by Django 3.1 on 2020-09-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_orderitemworkdelivery_orderitemworkhanging'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='delivery_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма доставка'),
        ),
        migrations.AddField(
            model_name='specification',
            name='hanging_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сумма развеска'),
        ),
    ]
