# Generated by Django 3.1 on 2020-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_auto_20200924_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_state',
            field=models.IntegerField(choices=[(0, 'Не заказаны'), (1, 'Заказаны'), (2, 'Оплачены'), (3, 'Отгружены')], default=0, verbose_name='Состояние по работам'),
        ),
    ]
