# Generated by Django 3.1 on 2020-09-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0002_auto_20200925_0651'),
        ('orders', '0072_auto_20200924_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtextile1',
            name='markup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markup.markupmaterialcategory', verbose_name='Наценка'),
        ),
    ]
