# Generated by Django 3.1 on 2020-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0073_orderitemtextile1_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='markup',
            field=models.FloatField(default=1, max_length=100, verbose_name='Наценка'),
        ),
    ]
