# Generated by Django 3.1 on 2020-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_auto_20200925_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True, verbose_name='Скидка'),
        ),
    ]
