# Generated by Django 3.1 on 2020-09-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcornice',
            name='markup',
            field=models.FloatField(default=1, max_length=100, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='orderitemworkassembly',
            name='markup',
            field=models.FloatField(default=1, max_length=100, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='orderitemworkdelivery',
            name='markup',
            field=models.FloatField(default=1, max_length=100, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='orderitemworkhanging',
            name='markup',
            field=models.FloatField(default=1, max_length=100, verbose_name='Наценка'),
        ),
        migrations.AddField(
            model_name='orderitemworksewing',
            name='markup',
            field=models.FloatField(default=1, max_length=100, verbose_name='Наценка'),
        ),
    ]
