# Generated by Django 3.1 on 2020-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_auto_20200928_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='type_p',
            field=models.IntegerField(choices=[(0, 'Доход'), (1, 'Расход')], default=0, verbose_name='Вид'),
        ),
    ]
