# Generated by Django 3.1 on 2020-09-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0078_paymentcategory_type_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type_p',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type_pay',
        ),
    ]
