# Generated by Django 3.1 on 2020-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress',
            field=models.IntegerField(choices=[(0, 0), (1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60), (7, 70), (8, 80), (9, 90), (10, 100), (11, 0)], default=0, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланирован'), (1, 'КП подготовлено'), (2, 'КП утверждено'), (3, 'Договор подготовлен'), (4, 'Договор подписан'), (5, 'Аванс получен'), (6, 'Материалы заказаны'), (7, 'Материалы оплачены'), (8, 'Материалы отгружены'), (9, 'Работы заказаны'), (10, 'Заказ выдан'), (11, 'Архив')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_css',
            field=models.IntegerField(choices=[(0, 'secondary'), (1, 'secondary'), (2, 'secondary'), (3, 'info'), (4, 'info'), (5, 'primary'), (6, 'primary'), (7, 'primary'), (8, 'primary'), (9, 'primary'), (10, 'success'), (11, 'warning')], default=0, verbose_name='Статус'),
        ),
    ]
