# Generated by Django 3.1 on 2020-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0082_auto_20201004_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
    ]
