# Generated by Django 3.1 on 2020-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0083_order_date_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_finished',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
    ]
