# Generated by Django 3.1 on 2020-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_s',
            field=models.IntegerField(choices=[(0, 'Нет скидки'), (1, 'Не согласованна'), (2, 'Согласованна'), (3, 'Отказано')], default=0, verbose_name='Статус скидки'),
        ),
    ]
