# Generated by Django 3.1 on 2020-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_order_discount_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_view',
            field=models.IntegerField(default=0, verbose_name='Просмотр скидки'),
        ),
    ]
