# Generated by Django 3.1 on 2020-10-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0087_order_discount_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=1, max_length=100, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_s',
            field=models.IntegerField(choices=[(0, 'Нет скидки'), (1, 'Не согласована'), (2, 'Согласована'), (3, 'Отказано')], default=0, verbose_name='Статус скидки'),
        ),
    ]
