# Generated by Django 3.1 on 2020-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_auto_20201014_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_s',
            new_name='discount_c_s',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_c',
            field=models.FloatField(blank=True, default=1, max_length=100, null=True, verbose_name='Скидка к карнизам'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_t',
            field=models.FloatField(blank=True, default=1, max_length=100, null=True, verbose_name='Скидка к текстилю'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_t_s',
            field=models.IntegerField(choices=[(0, 'Нет скидки'), (1, 'Не согласована'), (2, 'Согласована'), (3, 'Отказано')], default=0, verbose_name='Статус скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_w',
            field=models.FloatField(blank=True, default=1, max_length=100, null=True, verbose_name='Скидка к работам'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_w_s',
            field=models.IntegerField(choices=[(0, 'Нет скидки'), (1, 'Не согласована'), (2, 'Согласована'), (3, 'Отказано')], default=0, verbose_name='Статус скидки'),
        ),
    ]
