# Generated by Django 3.1 on 2020-10-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0089_auto_20201023_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_status',
            field=models.IntegerField(choices=[(0, 'Нет скидки'), (1, 'Ожидание согласования'), (2, 'Согласована'), (3, 'Отказано'), (4, 'Частичное согласование')], default=0, verbose_name='Общий статус скидки'),
        ),
    ]
