# Generated by Django 3.1 on 2020-11-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0090_order_discount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemcornice',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitemtextile1',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitemworkassembly',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitemworkdelivery',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitemworkhanging',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitemworksewing',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
    ]
