# Generated by Django 3.1 on 2020-11-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20201108_2226'),
        ('orders', '0091_auto_20201101_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcornice',
            name='additional',
            field=models.ManyToManyField(to='materials.CorniceAdditional', verbose_name='Допы'),
        ),
    ]
