# Generated by Django 3.1 on 2020-11-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20201108_2226'),
        ('orders', '0092_orderitemcornice_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCorniceAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Версия')),
                ('quantity', models.FloatField(default=1, verbose_name='Количество')),
                ('markup', models.FloatField(default=1, max_length=100, verbose_name='Наценка')),
                ('ordered', models.IntegerField(choices=[(0, 'Не заказан'), (1, 'Заказ отправлен'), (2, 'Заказан'), (3, 'Оплачен'), (4, 'Отгружены'), (5, 'В наличии'), (6, 'Отсутствует у поставщика')], default=0, verbose_name='Состояние заказа')),
                ('ordered_icon', models.IntegerField(choices=[(0, 'fa-circle-thin'), (1, 'target'), (2, 'disc'), (3, 'dollar-sign'), (4, 'arrow-down-circle'), (5, 'arrow-down-circle'), (6, 'alert-circle')], default=0, verbose_name='Состояние заказа icon')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.corniceadditional', verbose_name='Доп')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.specification', verbose_name='Спецификация')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitemcornice',
            name='additional',
            field=models.ManyToManyField(to='orders.OrderItemCorniceAdditional', verbose_name='Допы'),
        ),
    ]
