# Generated by Django 3.1 on 2020-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0093_auto_20201109_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemcornice',
            name='additional',
            field=models.ManyToManyField(default=None, to='orders.OrderItemCorniceAdditional', verbose_name='Допы'),
        ),
    ]
