# Generated by Django 3.1 on 2020-11-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0094_auto_20201109_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemcornice',
            name='additional',
        ),
    ]
