# Generated by Django 3.1 on 2020-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20201119_1445'),
        ('orders', '0095_remove_orderitemcornice_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemcorniceadditional',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.corniceadditionaloptions', verbose_name='Доп'),
        ),
    ]
