# Generated by Django 3.1 on 2020-11-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20201119_1445'),
        ('orders', '0096_auto_20201120_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcorniceadditional',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.cornicecollectioncolor', verbose_name='Цвет'),
        ),
    ]
