# Generated by Django 3.1 on 2020-11-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0097_orderitemcorniceadditional_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierordercornice',
            name='additional',
            field=models.ManyToManyField(to='orders.OrderItemCorniceAdditional', verbose_name='Заказанный доп материал'),
        ),
    ]
