# Generated by Django 3.1 on 2020-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0098_supplierordercornice_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermail',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='suppliermail',
            name='text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Текст письма'),
        ),
    ]
