# Generated by Django 3.1 on 2020-11-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0099_auto_20201123_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliermail',
            name='supplier',
        ),
    ]
