# Generated by Django 3.1 on 2020-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0100_remove_suppliermail_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermail',
            name='type_p',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Тип'),
        ),
    ]
