# Generated by Django 3.1 on 2020-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0101_suppliermail_type_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdoc',
            name='contract_p1',
            field=models.FileField(blank=True, upload_to='contract'),
        ),
        migrations.AddField(
            model_name='orderdoc',
            name='contract_p2',
            field=models.FileField(blank=True, upload_to='contract'),
        ),
        migrations.AddField(
            model_name='orderdoc',
            name='contract_p3',
            field=models.FileField(blank=True, upload_to='contract'),
        ),
        migrations.AddField(
            model_name='orderdoc',
            name='contract_p4',
            field=models.FileField(blank=True, upload_to='contract'),
        ),
        migrations.AddField(
            model_name='orderdoc',
            name='contract_p5',
            field=models.FileField(blank=True, upload_to='contract'),
        ),
    ]
