# Generated by Django 3.1 on 2020-12-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0102_auto_20201202_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='work_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность работ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_start',
            field=models.CharField(blank=True, default=5, max_length=100, null=True, verbose_name='Начало работ (через)'),
        ),
    ]
