# Generated by Django 3.1 on 2020-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0104_auto_20201218_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='comment1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='comment2',
        ),
        migrations.AddField(
            model_name='specification',
            name='comment1',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment1'),
        ),
        migrations.AddField(
            model_name='specification',
            name='comment2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment1'),
        ),
    ]
