# Generated by Django 3.1 on 2020-12-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0105_auto_20201218_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtextile1',
            name='designation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Обозначение'),
        ),
    ]
