# Generated by Django 3.1 on 2020-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupCustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_t', models.IntegerField(choices=[(0, 'От Партнеров'), (1, 'Социальные сети'), (2, 'Маркетплейс'), (3, 'Телефон'), (4, 'Салон')], default=0, verbose_name='Источник')),
                ('markup', models.FloatField(default=1, max_length=100, verbose_name='Наценка')),
            ],
        ),
        migrations.CreateModel(
            name='MarkupMaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_t', models.IntegerField(choices=[(0, 'Текстиль'), (1, 'Карнизы')], default=0, verbose_name='Источник')),
                ('markup', models.FloatField(default=1, max_length=100, verbose_name='Наценка')),
            ],
        ),
        migrations.CreateModel(
            name='MarkupWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_t', models.IntegerField(choices=[(0, 'Пошив'), (1, 'Монтаж'), (2, 'Развеска штор'), (3, 'Доставка')], default=0, verbose_name='Источник')),
                ('markup', models.FloatField(default=1, max_length=100, verbose_name='Наценка')),
            ],
        ),
    ]
