# Generated by Django 3.1 on 2020-09-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('markup', models.FloatField(default=1, max_length=100, verbose_name='Наценка')),
            ],
        ),
        migrations.AlterField(
            model_name='markupcustomercategory',
            name='source_t',
            field=models.IntegerField(choices=[(0, 'От Партнеров'), (1, 'Социальные сети'), (2, 'Маркетплейс'), (3, 'Телефон'), (4, 'Салон')], default=0, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='markupmaterialcategory',
            name='source_t',
            field=models.IntegerField(choices=[(0, 'Текстиль'), (1, 'Карнизы')], default=0, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='markupworkcategory',
            name='source_t',
            field=models.IntegerField(choices=[(0, 'Пошив'), (1, 'Монтаж'), (2, 'Развеска штор'), (3, 'Доставка')], default=0, verbose_name='Категория'),
        ),
    ]
