# Generated by Django 3.1 on 2020-11-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0002_auto_20200925_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.IntegerField(default=0, max_length=100, verbose_name='Значение')),
            ],
        ),
    ]
