# Generated by Django 3.1 on 2020-11-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0003_markupsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markupsetting',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
    ]
