# Generated by Django 3.1 on 2020-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0004_auto_20201109_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
            ],
        ),
    ]
