# Generated by Django 3.1 on 2020-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0005_markupcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markupsetting',
            name='value',
            field=models.FloatField(default=0, verbose_name='Значение'),
        ),
    ]
