# Generated by Django 3.1 on 2020-08-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Работы')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=100, verbose_name='Работы')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('type_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.typework', verbose_name='Тип работ')),
            ],
        ),
    ]
