# Generated by Django 3.1 on 2020-10-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0079_auto_20200930_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderedTextile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=100, verbose_name='Цена поставщика')),
                ('receipt', models.CharField(max_length=100, verbose_name='Счет')),
                ('status', models.IntegerField(choices=[(0, 'Не оплачено'), (1, 'Оплачено')], default=0, verbose_name='Состояние заказа')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitemtextile1', verbose_name='Позиция')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
