# Generated by Django 3.1 on 2020-10-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0084_auto_20201007_0017'),
        ('manager', '0002_supplierorderedtextile_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderedCornice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=100, verbose_name='Цена поставщика')),
                ('receipt', models.CharField(max_length=100, verbose_name='Счет')),
                ('status', models.IntegerField(choices=[(0, 'Не оплачено'), (1, 'Оплачено')], default=0, verbose_name='Состояние заказа')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitemcornice', verbose_name='Позиция')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
