# Generated by Django 3.1 on 2020-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_supplierorderedcornice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderedtextile',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип'),
        ),
    ]
