# Generated by Django 3.1 on 2020-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_supplierorderedcornice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderedcornice',
            name='type',
            field=models.CharField(default='Карнизы', max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='supplierorderedtextile',
            name='type',
            field=models.CharField(default='Текстиль', max_length=100, verbose_name='Тип'),
        ),
    ]
