# Generated by Django 3.1 on 2020-11-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0097_orderitemcorniceadditional_color'),
        ('manager', '0006_auto_20201009_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderedcornice',
            name='additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitemcorniceadditional', verbose_name='Позиция-доп'),
        ),
    ]
