# Generated by Django 3.1 on 2020-11-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_supplierorderedcornice_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderedcornice',
            name='date_shipped',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AddField(
            model_name='supplierorderedtextile',
            name='date_shipped',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
